sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
script:
  - hexo generate # generate static files
after_script:
  - cd ./public
  - git init
  - git config user.name "litiezhu"
  - git config user.email"lk0219@foxmail.com"
  - git add .
  - git commit -m "$TRAVIS_BUILD_NUMBER"
  - git push --force --set-upstream --quiet "https://nuimrfSUqU:${CO_TOKEN}@e.coding.net/litiezhu/litiezhu.coding.me.git":master master
  - rm -rf ./.git
  - cd ..

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: source
  target_branch: master
  local-dir: public